@startuml

class PlantGrid {
    --
    rows:PlantCell[][]
}

class PlantCell {
    cellIndex:CellIndex
    equipment:Equipment
    emptyNeighbours:Object
    addEquipment(cellIndex:CellIndex, direction:NeighbourDirection)
    removeEquipment(cellIndex:CellIndex)
    --
}

class Equipment {
    type:EquipmentType
}

class AddEquipment {
    addEquipment(type:EquipmentType)
    --
}

PlantGrid -- "0..n" PlantCell
PlantGrid -- AddEquipment
PlantCell -- "0..1" Equipment

@enduml